version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgresql
    container_name: trkmaq
    env_file:
      - .env
    ports:
      - ${PROCESS_PORT}:${PROCESS_PORT}
  postgresql:
    image: postgres:15-alpine
    container_name: postgresql_trkmaq
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=${DATABASE_INITDB_ARGS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test-postgresql:
    image: postgres:15-alpine
    container_name: postgresql_trkmaq_test
    restart: always
    ports:
      - ${DATABASE_PORT_TEST}:5432
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
      - POSTGRES_INITDB_ARGS=${DATABASE_INITDB_ARGS}
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data_test: